# Generated by Django 5.2.4 on 2025-07-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('user_answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exam.examresult')),
            ],
        ),
    ]
