# Generated by Django 5.2.4 on 2025-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_examquestionresponse_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
