# Generated by Django 5.2.4 on 2025-07-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_examresult_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='details',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='ExamQuestionResponse',
        ),
    ]
