# Generated by Django 5.2.4 on 2025-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_examresult_details_delete_examquestionresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
