# Generated by Django 5.2.4 on 2025-07-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, help_text='Temporary OTP for email verification', max_length=10, null=True),
        ),
    ]
