# Generated by Django 5.2.4 on 2025-07-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
