# Generated by Django 5.2.4 on 2025-07-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_input_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
    ]
