# Generated by Django 5.2.4 on 2025-07-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_input'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
