# Generated by Django 5.2.4 on 2025-07-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examquestionresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestionresponse',
            name='correct_answer',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='examquestionresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examquestionresponse',
            name='user_answer',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
